
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



class Login() :
    def __init__(self,root) :
        self.OUTPUT_PATH = Path(__file__).parent
        self.ASSETS_PATH = self.OUTPUT_PATH / Path("./assets")



        self.window = Tk()

        self.window.geometry("1000x600")
        self.window.configure(bg = "#E6E6E6")


        self.canvas = Canvas(
            window,
            bg = "#E6E6E6",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        self.image_1 = canvas.create_image(
            554.0,
            355.0,
            image=self.image_image_1
        )

        self.canvas.create_rectangle(
            284.0,
            78.0,
            716.0,
            509.0,
            fill="#FFFFFF",
            outline="")

        self.canvas.create_text(
            438.0,
            105.0,
            anchor="nw",
            text="LOGIN",
            fill="#000000",
            font=("Inter Bold", 40 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(
            x=426.0,
            y=406.0,
            width=134.0,
            height=47.0
        )

        self.canvas.create_text(
            326.0,
            198.0,
            anchor="nw",
            text="ENTER MAIL",
            fill="#000000",
            font=("Inter Bold", 15 * -1)
        )

        self.canvas.create_text(
            326.0,
            293.0,
            anchor="nw",
            text="ENTER PASSWORD",
            fill="#000000",
            font=("Inter Bold", 15 * -1)
        )

        self.entry_image_1 = PhotoImage(
            file=self.relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            496.0,
            339.0,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            highlightthickness=0
        )
        self.entry_1.place(
            x=326.0,
            y=315.0,
            width=340.0,
            height=46.0
        )

        self.entry_image_2 = PhotoImage(
            file=self.relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            496.0,
            248.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            bd=0,
            bg="#FFFFFF",
            highlightthickness=0
        )
        self.entry_2.place(
            x=326.0,
            y=224.0,
            width=340.0,
            height=46.0
        )
        self.window.resizable(False, False)
        self.window.mainloop()

    def relative_to_assets(self,path: str) -> Path:
        return self.ASSETS_PATH / Path(path)